Revert of Enable strict coverage for step module (patchset #3 id:40001 of https://codereview.chromium.org/2806363004/ )
Reason for revert:
Fails downstream, e.g. build:

Exception: While generating results for 'swarming:tests/results_merger_unittest': TypeError: 'NoneType' object is not callable

Looks like it's picking up unrelated swarming tests...

Original issue's description:
> Enable strict coverage for step module
>
> BUG=chromium:693058
>
> Review-Url: https://codereview.chromium.org/2806363004
> Committed: https://github.com/luci/recipes-py/commit/3bd327959845d8cb93d1987b3da790a20384a1e1

TBR=iannucci@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:693058

Review-Url: https://codereview.chromium.org/2814873002