Improve the exception for missing config.
When there is an issue with a missing config (due perhaps to a typo or
missing a module that adds configurations to dependency modules), the
exception provides little information to help the user diagnose the
problem.

Currently a missing config passed to
to set_config/make_config/make_config_params results in an exception
similar to:
KeyError: 'chrome_from_release_buildspec'

Currently a missing config passed to apply_config results in an
exception similar to:
AssertionError(('chrome_from_release_buildspec', {'crashpad':
<function crashpad at 0x7f1f9d939c08>, 'chromium_perf_clang': <function
chromium_perf_clang at 0x7f1f9d6b7230>, ...}),)

Both errors are now changed to the following form that includes
information about what module and only the names for the config items:

KeyError: chrome_from_release_buildspec is not the name of a
configuration for module RECIPE_MODULES.depot_tools.gclient: ['android',
'angle', 'boringssl', 'build', 'build_internal', ...]
Change-Id: I1c126a5a9311a7026cd05e3b98c17257bc0e1e85
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/1754630
Commit-Queue: Garrett Beaty <gbeaty@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>