Revert "Check Content-Length when downloading"
This reverts commit d992bd75dcf1ebf0cf33231d04069887ea048cc9.

Reason for revert: irm/i_7B1qmn5hzfQ17yY27XJu

  File "/Volumes/Work/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/url/resources/pycurl.py", line 81, in _download
    raise ValueError('Expected content length: %d, downloaded: %d' %
TypeError: %d format: a number is required, not str


Original change's description:
> Check Content-Length when downloading
>
> This is a workaround for requests not checking the Content-Length, which
> leads to recipes treat download failures as successes.
>
> Bug:1370057
> Change-Id: I7e6e6916c5e3b91e85c4c6efd455cf8f0aee92d1
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/4167114
> Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
> Commit-Queue: Chenlin Fan <fancl@chromium.org>

Bug: 1370057
Change-Id: I34b48ce51f2c39628c944c0d4c0c1156c3d85bbf
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/4290727
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Chenlin Fan <fancl@chromium.org>
Auto-Submit: Garth Bryden <garthbryden@google.com>
Owners-Override: Sung-Chi Li <lschyi@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>