[recipes.py] Fix crash when run with no subcommand in py3
When `recipes.py` is run in a py3-only repo with no subcommand, it fails
unhelpfully:

  $ ./recipes.py
  Traceback (most recent call last):
    File ".recipe_deps/recipe_engine/main.py", line 153, in _main
      ret = parse_and_run()
    File ".recipe_deps/recipe_engine/recipe_engine/internal/commands/__init__.py", line 310, in parse_and_run
      return args.func(args)
  AttributeError: 'Namespace' object has no attribute 'func'

This is apparently a known bug in Python
(https://bugs.python.org/issue16308) that can be worked around by
calling `add_subparsers` with `required=True`, which changes the error
to the following:

  $ ./recipes.py
  usage: <elided>
  main.py: error: the following arguments are required: command

which is not exactly the same as, but close enough to, the error message
you get when running it under Python 2:

  $ ./recipes.py
  usage: <elided>
  main.py: error: too few arguments

Change-Id: I9f8f12db540d665b689b3548dc4eac31d70e04c6
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/4348222
Commit-Queue: Robbie Iannucci <iannucci@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>
Commit-Queue: Gregory Nisbet <gregorynisbet@google.com>
Auto-Submit: Oliver Newman <olivernewman@google.com>