Revert "Require explicit API/TEST_API exports."
This reverts commit 2cbdab1507845011d4a6a398a76534a492ee1a44.

Reason for revert: build recipe roller cannot roll change
https://ci.chromium.org/b/8701989573245622641/infra
recipe_engine.internal.exceptions.MalformedModuleError: Module "build/chromium_bootstrap" has RecipeTestApi subclass in `test_api`, but does not export API

Original change's description:
> Require explicit API/TEST_API exports.
>
> Also brush up the docs a bit.
>
> R=mohrr
>
> Bug: 448955620
> Change-Id: Ib71bf05d7aa82d5c041c321ac050ad33034a8283
> Recipe-Manual-Change: chromiumos
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/7007089
> Commit-Queue: Robbie Iannucci <iannucci@google.com>
> Reviewed-by: Rob Mohr <mohrr@google.com>
> Auto-Submit: Robbie Iannucci <iannucci@google.com>

Bug: 448955620
Change-Id: If6059a5cbc223ed8bb929c93dcbeada060c4fbbc
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/7014787
Auto-Submit: Garrett Beaty <gbeaty@google.com>
Commit-Queue: Robbie Iannucci <iannucci@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Robbie Iannucci <iannucci@google.com>