Also stringify environment var names.
This fixes a problem on Windows where unicode strings were causing the
error:
  TypeError: environment can only contain strings

R=stip@chromium.org, xusydoc@chromium.org
BUG=304949

Review URL: https://codereview.chromium.org/26259006

git-svn-id: svn://svn.chromium.org/chrome/trunk/tools/build@229438 0039d316-1c4b-4281-b951-d872f2087c98