Fix current test runner when tests crash.
A recent refactor switched the argument order for the worker function
leading to obscure stack traces when tests crash:

  Traceback (most recent call last):
    File "ENGINE/recipe_engine/main.py", line 76, in _main
      ret = parse_and_run()
    File "ENGINE/recipe_engine/internal/commands/__init__.py", line 277, in parse_and_run
      return args.func(args)
    File "ENGINE/recipe_engine/internal/commands/test/__init__.py", line 96, in _launch
      return main(args)
    File "ENGINE/recipe_engine/internal/commands/test/run_train.py", line 813, in main
      return run_run(args.filter, args.jobs, args.json, train_mode=False)
    File "ENGINE/recipe_engine/internal/commands/test/run_train.py", line 659, in run_run
      results_proto.test_failures[test_description.full_name].failures.extend([
  AttributeError: 'bool' object has no attribute 'full_name'
  Uncaught exception (AttributeError): 'bool' object has no attribute 'full_name'

This was because of the `worker` wrapper. Although this wrapper is going
away in an upcoming version of the simulation test runner, removing it now
is easy enough and fixes the error.

R=tandrii@chromium.org

Bug: 910369, 964141
Change-Id: I7f47912f8946325dc51b41e536c2eb1a6f289743
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/1618211
Commit-Queue: Robbie Iannucci <iannucci@chromium.org>
Commit-Queue: Andrii Shyshkalov <tandrii@chromium.org>
Auto-Submit: Robbie Iannucci <iannucci@chromium.org>
Reviewed-by: Andrii Shyshkalov <tandrii@chromium.org>