[engine] Improve error for missing test deps
Previously, accessing `api.foo` within a `GenTests` function when the
module "foo" hadn't been added as to the recipe's DEPS would yield:

  AttributeError: 'RecipeTestApi' object has no attribute 'foo'

This is confusing because it suggests that the code that references
`api.foo` is invalid, when in fact that code is fine and a new entry
just needs to be added to DEPS.

Now accessing an un-imported recipe module from `GenTests` yields:

  recipe_engine.util.ModuleInjectionError: Recipe has no dependency
  'foo'. (Add it to DEPS?)

...which is consistent with the messaging for missing DEPS accessed from
within `RunSteps` or from within a module.

Change-Id: Ib707e1b2b13633d20b7188359de0ca36681e040f
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/5070794
Commit-Queue: Oliver Newman <olivernewman@google.com>
Reviewed-by: Robbie Iannucci <iannucci@chromium.org>
Auto-Submit: Oliver Newman <olivernewman@google.com>