Revert of Assert validity of stream parameters. (patchset #4 id:60001 of https://codereview.chromium.org/2792333003/ )
Reason for revert:
Breaks downstream testing in tools/build repo.

Both simulation_test and test hang, and throw exceptions, e.g.:

ValueError: Failed assertion: Step text must not contain a newline. {'text': '<br/>\n===== PERF TRY JOB RESULTS =====\n\nTest Command: src/tools/perf/run_benchmark -v --browser=android-chrome --output-format=chartjson sunspider --upload-bucket=public\nTest Metric: dummy/dummy\nRelative Change: 88.88889%\nStandard Error: +- 0.00000 delta\n\nRevision    Mean        Std.Error\nPatch       1.0         0.0\nNo Patch    9.0         0.0\n<br/>'}

Original issue's description:
> Assert validity of stream parameters.
>
> Assert that stream parameters are valid. A lot of these validity checks
> are related to limitations in annotations (e.g., no newlines), but
> others are actually content errors. This adds assertions that:
>
> 1) No annotation parameter may include a newline in it. This is
>    disallowed because the annotation parser cannot handle multi-line
>    single annotations.
> 2) Build properties must be valid JSON. This is a requirement imposed by
>    the annotation parser (chromium_step.py), and will lead to total
>    waterfall breakages if invalid JSON is exported.
>
> This also adds unit tests to check that these assertions work.
>
> BUG=None
> TEST=unit
>
> Review-Url: https://codereview.chromium.org/2792333003
> Committed: https://github.com/luci/recipes-py/commit/ddfc94f01e4e1d3c7bf7dedfd58e6813bc5160df

TBR=iannucci@chromium.org,martiniss@chromium.org,tandrii@chromium.org,dnj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=None

Review-Url: https://codereview.chromium.org/2798223005