Revert of Enable recipe bootstrap by default (patchset #1 id:1 of https://codereview.chromium.org/2801073004/ )
Reason for revert:
Breaks in practice:

https://build.chromium.org/p/tryserver.chromium.mac/builders/mac_chromium_compile_dbg_ng/builds/391043

Activating environment: '/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV'
  Removing old environment: None
  Building new environment
  Activating environment
  Installing deps
    ndg_httpsclient: {'version': '0.4.2', 'gs': '03396d0b960c414e92ff355b4fe0fe210855fd58.tar.gz', 'build': '0'}
    pyOpenSSL: {'repo': 'external/github.com/pyca/pyopenssl', 'version': '0.14', 'rev': '496f40dca9a47c0f1dfe0cd841256485708c8442', 'build': '0'}
    coverage: {'repo': 'external/github.com/nedbat/coveragepy', 'version': '4.3.4', 'rev': '4dbcd5982eeb53a34bee17d9a4e539b222d1239e', 'build': '0'}

Done creating environment
Traceback (most recent call last):
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 762, in <module>
    ret = main()
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 678, in main
    return _real_main(args, op_args)
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 694, in _real_main
    from recipe_engine import package
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/package.py", line 18, in <module>
    from . import fetch
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/fetch.py", line 18, in <module>
    from . import requests_ssl
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/requests_ssl.py", line 8, in <module>
    import requests
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/third_party/requests/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/third_party/requests/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Uncaught exception (AttributeError): 'module' object has no attribute 'SSL_ST_INIT'
revert_cq: 1
revert_reason_textarea: Breaks in practice:

ctivating environment: '/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV'
  Removing old environment: None
  Building new environment
  Activating environment
  Installing deps
    ndg_httpsclient: {'version': '0.4.2', 'gs': '03396d0b960c414e92ff355b4fe0fe210855fd58.tar.gz', 'build': '0'}
    pyOpenSSL: {'repo': 'external/github.com/pyca/pyopenssl', 'version': '0.14', 'rev': '496f40dca9a47c0f1dfe0cd841256485708c8442', 'build': '0'}
    coverage: {'repo': 'external/github.com/nedbat/coveragepy', 'version': '4.3.4', 'rev': '4dbcd5982eeb53a34bee17d9a4e539b222d1239e', 'build': '0'}

Done creating environment
Traceback (most recent call last):
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 762, in <module>
    ret = main()
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 678, in main
    return _real_main(args, op_args)
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipes.py", line 694, in _real_main
    from recipe_engine import package
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/package.py", line 18, in <module>
    from . import fetch
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/fetch.py", line 18, in <module>
    from . import requests_ssl
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/requests_ssl.py", line 8, in <module>
    import requests
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/third_party/requests/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/third_party/requests/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/b/rr/tmpWyMAB5/rw/checkout/scripts/slave/.recipe_deps/recipe_engine/ENV/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Uncaught exception (AttributeError): 'module' object has no attribute 'SSL_ST_INIT'

Original issue's description:
> Enable recipe bootstrap by default
>
> Add --disable-bootstrap as override and escape hatch
>
> BUG=none
>
> Review-Url: https://codereview.chromium.org/2801073004
> Committed: https://github.com/luci/recipes-py/commit/e2b4fd5362e043dc66e85f5c342e414c5bfb89de

TBR=iannucci@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=709459

Review-Url: https://codereview.chromium.org/2805233002